# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 23:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
    ]
