# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 05:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetwork', '0002_auto_20170226_1813'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comm', models.CharField(max_length=160)),
                ('time', models.DateTimeField()),
                ('msg', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='socialnetwork.Message')),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
